# BREADS


@breadId = 6687006a56f38b4e8e315067
@breadsUrl = saltyBreads

###
GET http://localhost:3030/{{breadsUrl}} HTTP/1.1

###
GET http://localhost:3030/{{breadsUrl}}/{{breadId}} HTTP/1.1

###
POST http://localhost:3030/{{breadsUrl}} HTTP/1.1
Content-Type: application/json

{
  "name": "Cuchilla",
  "weight": 135,
  "left": 0,
  "make": 0
}

###
PUT http://localhost:3030/{{breadsUrl}}/{{breadId}} HTTP/1.1
Content-Type: application/json

{
  "name": "Bombon changed",
  "weight": 80,
  "left": 0,
  "make": 0
}

###
DELETE http://localhost:3030/{{breadsUrl}}/{{breadId}} HTTP/1.1


# SAVED BREADS


@savedBreadsId = 66875af841b533f95cf45f1b
@savedBreadsUrl = savedSaltyBreads

###
GET http://localhost:3030/{{savedBreadsUrl}} HTTP/1.1

###
GET http://localhost:3030/{{savedBreadsUrl}}/{{savedBreadsId}} HTTP/1.1

###
POST http://localhost:3030/{{savedBreadsUrl}} HTTP/1.1
Content-Type: application/json

{
  "date": "asdasd",
  "breads": [
    {
      "name": "Maiz",
      "weight": 80,
      "left": 0,
      "make": 0
    }
  ]
}

###
PUT http://localhost:3030/{{savedBreadsUrl}}/{{savedBreadsId}} HTTP/1.1
Content-Type: application/json

{
  "date": "zxcv",
  "breads": [
    {
      "name": "Bonbom",
      "weight": 80,
      "left": 0,
      "make": 0
    }
  ]
}

###
DELETE http://localhost:3030/{{savedBreadsUrl}}/{{savedBreadsId}} HTTP/1.1